name: GitHub Actions Demo
on: [push]
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: lacework/lw-scanner-action@v1.0.0
      name: Scan container images for vulnerabitilies using Lacework
      with:
        LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
        LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
        IMAGE_NAME: brianbyers/platform-info
        IMAGE_TAG: latest
        SAVE_RESULTS_IN_LACEWORK: true
        SAVE_BUILD_REPORT: true
        BUILD_REPORT_FILE_NAME: myreport.html