name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  build:
      steps:
          - uses: lacework/lw-scanner-action@v1.0.0
            name: Scan container images for vulnerabitilies using Lacework
            with:
              LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
              LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
              IMAGE_NAME: techallylw/vulnerable-container
              IMAGE_TAG: v0.0.1
              SAVE_RESULTS_IN_LACEWORK: true
              SAVE_BUILD_REPORT: true
              BUILD_REPORT_FILE_NAME: myreport.html